### ISSUE TITLE
idea

### ISSUE THREAD

**Issue by ethaniel** [Ornias1993/fetlife-aslsearch-reborn#65]
Dear Ornias,

I have an idea.

Since this script didn't work for me, and I'm a developer myself, how about we make a separate searchable database of fetlife accounts?

Basically, the tampermonkey script would only parse the fetlife pages that the user opens and scrapes all the information that the user sees about other users - page URL, age, avatar URL, sex, kink, etc and then POST to a remote database.

Then, the actual search would be against that database (without crawling fetlife). It would be super-fast and almost accurate.

Fetlife will not be happy about this, but we could host this on some bulletproof hosting.
I'm a PHP/Mysql developer and can help with the backend.

**Comment by Slofe** [comment]
It's not working for anyone at the moment I don't think. I'm under the impression it's still being worked on.
A searchable database was done years ago and there was a big hoo Har about it. If your proposed script only scrapes pages opened by people doesn't that sort of defeat the object of this script? I'd still have to trawl through everyone in my area and open their pages individually to get them added to the database plus it misses new people joining all the time, unless I've misunderstood you? 

If there was a way it can scrape everyone in a certain area once, add them to a database and some how not scrape them again the next time you run the script and only scrape new people added since the last time it was run? Now that would really, really be useful!
